
# high

bootstrap.servers:
        "kafka1:9092,kafka2:9092,kafka3:9092"

key.serializer:
        "org.apache.kafka.common.serialization.StringSerializer"

value.serializer:
        "org.apache.kafka.common.serialization.StringSerializer"

acks: "1"

retries: 0

## 32M
buffer.menory: 33554432

# medium

## 16K
batch.size: 16384

linger.ms: "1"


